namespace FirstApplicationAPI.DTO
{
    public class CustomerDTO
    {
        public int LegacyId { get; set; }
        public string FullName { get; set; }
        public string Nickname { get; set; }
        public string Address { get; set; }
        public string Neighborhood { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Complement { get; set; }
        public int? Residence { get; set; }
        public int? Type { get; set; }
        public int? Status { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Cellphone { get; set; }
        public string Email { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string Parentage { get; set; }
        public string MaritalStatus { get; set; }
        public string Spouse { get; set; }
        public string Profession { get; set; }
        public string Company { get; set; }
        public long? Income { get; set; }
        public long? Limit { get; set; }
        public string SalespersonCode { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public DateTime? LastPurchaseDate { get; set; }
        public string Birthdate { get; set; }
        public string RegionCode { get; set; }
        public string AgreementCode { get; set; }
        public string UserCode { get; set; }
        public string Number { get; set; }
        public string RgOrgan { get; set; }
        public string RgState { get; set; }
        public DateTime? RgIssuanceDate { get; set; }
        public string Gender { get; set; }
        public DateTime? Forecast { get; set; }
        public string CNAE { get; set; }
        public string IBGEMunicipalityCode { get; set; }
        public string IBGE { get; set; }
        public string PantsSize { get; set; }
        public string BlouseSize { get; set; }
        public string ShoeSize { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string CorrespondenceNeighborhood { get; set; }
        public string CorrespondenceCity { get; set; }
        public string CorrespondenceState { get; set; }
        public string CorrespondenceZipCode { get; set; }
        public string CorrespondenceComplement { get; set; }
        public string ProducerRg { get; set; }
        public string Responsible1Name { get; set; }
        public string Responsible1CPF { get; set; }
        public string Responsible1RG { get; set; }
        public string Responsible1Profession { get; set; }
        public string Responsible1MaritalStatus { get; set; }
        public string Responsible1Address { get; set; }
        public string Responsible1Neighborhood { get; set; }
        public string Responsible1City { get; set; }
        public string Responsible1State { get; set; }
        public string Responsible1ZipCode { get; set; }
        public string Responsible2Name { get; set; }
        public string Responsible2CPF { get; set; }
        public string Responsible2RG { get; set; }
        public string Responsible2Profession { get; set; }
        public string Responsible2MaritalStatus { get; set; }
        public string Responsible2Address { get; set; }
        public string Responsible2Neighborhood { get; set; }
        public string Responsible2City { get; set; }
        public string Responsible2State { get; set; }
        public string Responsible2ZipCode { get; set; }
        public string Photo { get; set; }
        public string PaymentCondition { get; set; }
        public string IEType { get; set; }
        public string FinalConsumer { get; set; }
        public string BranchCode { get; set; }
    }
}
